<?php
namespace DTB\CalculatorPdf;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * ============================================================================
 * REPORT CONTRACT (POST body to /wp-json/dtb/v1/calculators/export-pdf)
 * ============================================================================
 * {
 *   "project": {
 *     "jobName": "string", "jobAddress": "string", "contractorName": "string",
 *     "estimatorName": "string", "date": "YYYY-MM-DD", "notes": "string"
 *   },
 *   "sections": [
 *     {
 *       "key": "sheets|compound|tape|bead|screws|summary",
 *       "title": "Drywall Sheets",
 *       "inputs":  [ { "label": "Sheet Size", "value": "4x12 ft" }, ... ],
 *       "items":   [ { "label": "Wall 1", "value": "12 ft x 9 ft" },
 *                    { "label": "1/2\" Drywall Sheet", "qty": 12, "unit": "ea",
 *                      "unitCost": 14.50, "lineTotal": 174.00 }, ... ],
 *       "results": [ { "label": "Sheets Needed", "value": 18, "highlight": true } ]
 *     }, ...
 *   ]
 * }
 *
 * Row object keys are all optional except "label"; renderer only draws columns
 * that are present anywhere in that row group, so plain label/value rows and
 * priced BOM rows can coexist across different sections.
 * ============================================================================
 */

const ACCENT       = '#E8501A'; // safety orange — brand accent
const INK_DARK     = '#0D0E12'; // header band
const INK_MUTED    = '#5B6270';
const BORDER_LIGHT = '#E3E5E9';
const FILL_LIGHT   = '#F7F7F8';

function render_report_html( array $data ): string {
    $project  = $data['project'];
    $sections = $data['sections'];

    $company_name = 'Drywall Toolbox';
    $generated_at = current_time( 'F j, Y g:i A' );

    ob_start();
    ?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style><?php echo report_css(); ?></style>
</head>
<body>

    <table class="header-band" role="presentation">
        <tr>
            <td class="header-brand"><?php echo esc_html( $company_name ); ?></td>
            <td class="header-title">JOB ESTIMATE REPORT</td>
        </tr>
    </table>

    <?php echo build_project_meta( $project, $generated_at ); ?>

    <?php foreach ( $sections as $section ) : ?>
        <?php echo build_section( $section ); ?>
    <?php endforeach; ?>

    <div class="disclaimer">
        Quantities are estimates based on user-entered dimensions and standard waste factors.
        Verify measurements on site before ordering materials. Generated by Drywall Toolbox
        Job Calculators — drywalltoolbox.com
    </div>

</body>
</html>
    <?php
    return ob_get_clean();
}

function build_project_meta( array $project, string $generated_at ): string {
    $rows = [
        [ 'Job Name', $project['jobName'] ],
        [ 'Job Address', $project['jobAddress'] ],
        [ 'Contractor', $project['contractorName'] ],
        [ 'Estimator', $project['estimatorName'] ],
        [ 'Date', $project['date'] ],
        [ 'Generated', $generated_at ],
    ];

    ob_start();
    ?>
    <table class="meta-box" role="presentation">
        <?php foreach ( array_chunk( $rows, 2 ) as $pair ) : ?>
        <tr>
            <?php foreach ( $pair as $cell ) : ?>
            <td class="meta-label"><?php echo esc_html( $cell[0] ); ?></td>
            <td class="meta-value"><?php echo esc_html( $cell[1] !== '' ? $cell[1] : '—' ); ?></td>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php if ( ! empty( $project['notes'] ) ) : ?>
    <table class="notes-box" role="presentation">
        <tr><td class="notes-label">Notes</td></tr>
        <tr><td class="notes-value"><?php echo nl2br( esc_html( $project['notes'] ) ); ?></td></tr>
    </table>
    <?php endif; ?>
    <?php
    return ob_get_clean();
}

function build_section( array $section ): string {
    $is_summary = ( $section['key'] === 'summary' );

    ob_start();
    ?>
    <table class="section" role="presentation">
        <tr><td class="section-title"><?php echo esc_html( $section['title'] ); ?></td></tr>
    </table>

    <?php if ( ! empty( $section['inputs'] ) ) : ?>
        <?php echo build_two_col_table( $section['inputs'], 'inputs-table' ); ?>
    <?php endif; ?>

    <?php if ( ! empty( $section['items'] ) ) : ?>
        <?php echo $is_summary
            ? build_bom_table( $section['items'] )
            : build_items_table( $section['items'] ); ?>
    <?php endif; ?>

    <?php if ( ! empty( $section['results'] ) ) : ?>
        <?php echo build_results_row( $section['results'] ); ?>
    <?php endif; ?>
    <?php
    return ob_get_clean();
}

function build_two_col_table( array $rows, string $class ): string {
    ob_start();
    ?>
    <table class="<?php echo esc_attr( $class ); ?>" role="presentation">
        <?php foreach ( array_chunk( $rows, 2 ) as $pair ) : ?>
        <tr>
            <?php foreach ( $pair as $row ) : ?>
            <td class="dt-label"><?php echo esc_html( $row['label'] ); ?></td>
            <td class="dt-value"><?php echo esc_html( format_value( $row['value'] ?? '' ) ); ?></td>
            <?php endforeach; ?>
            <?php if ( count( $pair ) === 1 ) : ?>
            <td class="dt-label"></td><td class="dt-value"></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php
    return ob_get_clean();
}

function build_items_table( array $items ): string {
    $has_qty  = array_reduce( $items, fn( $c, $i ) => $c || isset( $i['qty'] ), false );
    $has_unit = array_reduce( $items, fn( $c, $i ) => $c || isset( $i['unit'] ), false );

    ob_start();
    ?>
    <table class="items-table" role="presentation">
        <thead>
            <tr>
                <th class="col-label">Item</th>
                <?php if ( $has_qty ) : ?><th class="col-num">Qty</th><?php endif; ?>
                <?php if ( $has_unit ) : ?><th class="col-unit">Unit</th><?php endif; ?>
                <?php if ( ! $has_qty && ! $has_unit ) : ?><th class="col-val">Value</th><?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ( $items as $i => $item ) : ?>
            <tr class="<?php echo $i % 2 === 1 ? 'row-alt' : ''; ?>">
                <td class="col-label"><?php echo esc_html( $item['label'] ); ?></td>
                <?php if ( $has_qty ) : ?><td class="col-num"><?php echo esc_html( format_value( $item['qty'] ?? '' ) ); ?></td><?php endif; ?>
                <?php if ( $has_unit ) : ?><td class="col-unit"><?php echo esc_html( $item['unit'] ?? '' ); ?></td><?php endif; ?>
                <?php if ( ! $has_qty && ! $has_unit ) : ?><td class="col-val"><?php echo esc_html( format_value( $item['value'] ?? '' ) ); ?></td><?php endif; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php
    return ob_get_clean();
}

/** Bill-of-materials style table for the Summary section — adds cost columns when priced. */
function build_bom_table( array $items ): string {
    $has_cost = array_reduce( $items, fn( $c, $i ) => $c || isset( $i['unitCost'] ), false );
    $grand    = 0.0;

    ob_start();
    ?>
    <table class="bom-table" role="presentation">
        <thead>
            <tr>
                <th class="col-label">Item</th>
                <th class="col-num">Qty</th>
                <th class="col-unit">Unit</th>
                <?php if ( $has_cost ) : ?>
                <th class="col-num">Unit Cost</th>
                <th class="col-num">Line Total</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ( $items as $i => $item ) :
                $line_total = $item['lineTotal'] ?? null;
                if ( $has_cost && is_numeric( $line_total ) ) {
                    $grand += (float) $line_total;
                }
            ?>
            <tr class="<?php echo $i % 2 === 1 ? 'row-alt' : ''; ?>">
                <td class="col-label"><?php echo esc_html( $item['label'] ); ?></td>
                <td class="col-num"><?php echo esc_html( format_value( $item['qty'] ?? '' ) ); ?></td>
                <td class="col-unit"><?php echo esc_html( $item['unit'] ?? '' ); ?></td>
                <?php if ( $has_cost ) : ?>
                <td class="col-num"><?php echo esc_html( format_currency( $item['unitCost'] ?? null ) ); ?></td>
                <td class="col-num"><?php echo esc_html( format_currency( $line_total ) ); ?></td>
                <?php endif; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php if ( $has_cost ) : ?>
        <tfoot>
            <tr class="grand-total-row">
                <td colspan="4" class="col-label grand-total-label">Estimated Material Total</td>
                <td class="col-num grand-total-value"><?php echo esc_html( format_currency( $grand ) ); ?></td>
            </tr>
        </tfoot>
        <?php endif; ?>
    </table>
    <?php
    return ob_get_clean();
}

function build_results_row( array $results ): string {
    ob_start();
    ?>
    <?php foreach ( array_chunk( $results, 4 ) as $row ) : ?>
    <table class="results-row" role="presentation">
        <tr>
            <?php foreach ( $row as $result ) : ?>
            <td class="result-cell <?php echo ! empty( $result['highlight'] ) ? 'result-highlight' : ''; ?>">
                <div class="result-label"><?php echo esc_html( $result['label'] ); ?></div>
                <div class="result-value"><?php echo esc_html( format_value( $result['value'] ?? '' ) ); ?></div>
            </td>
            <?php endforeach; ?>
            <?php for ( $i = count( $row ); $i < 4; $i++ ) : ?>
            <td class="result-cell result-cell-empty"></td>
            <?php endfor; ?>
        </tr>
    </table>
    <?php endforeach; ?>
    <?php
    return ob_get_clean();
}

function format_value( $value ): string {
    if ( is_numeric( $value ) ) {
        return ( floor( $value ) == $value ) ? (string) (int) $value : number_format( (float) $value, 2 );
    }
    return (string) $value;
}

function format_currency( $value ): string {
    return is_numeric( $value ) ? '$' . number_format( (float) $value, 2 ) : '—';
}

function report_css(): string {
    return '
    * { box-sizing: border-box; }
    body { font-family: Helvetica, Arial, sans-serif; color: #1B1D22; font-size: 10.5px; margin: 0; padding: 24px 36px 60px; }

    table { border-collapse: collapse; width: 100%; }

    .header-band { margin-bottom: 14px; }
    .header-brand { background: ' . INK_DARK . '; color: #FFFFFF; font-size: 16px; font-weight: bold; padding: 14px 16px; width: 55%; }
    .header-title { background: ' . ACCENT . '; color: #FFFFFF; font-size: 12px; font-weight: bold; letter-spacing: 1px; text-align: right; padding: 14px 16px; }

    .meta-box { margin-bottom: 6px; border: 1px solid ' . BORDER_LIGHT . '; }
    .meta-label { background: ' . FILL_LIGHT . '; font-weight: bold; color: ' . INK_MUTED . '; text-transform: uppercase; font-size: 8px; padding: 6px 8px; width: 15%; border: 1px solid ' . BORDER_LIGHT . '; }
    .meta-value { padding: 6px 8px; width: 35%; border: 1px solid ' . BORDER_LIGHT . '; }

    .notes-box { margin-bottom: 16px; border: 1px solid ' . BORDER_LIGHT . '; }
    .notes-label { background: ' . FILL_LIGHT . '; font-weight: bold; color: ' . INK_MUTED . '; text-transform: uppercase; font-size: 8px; padding: 6px 8px; border: 1px solid ' . BORDER_LIGHT . '; }
    .notes-value { padding: 8px; border: 1px solid ' . BORDER_LIGHT . '; }

    .section { margin-top: 18px; margin-bottom: 6px; }
    .section-title { border-left: 4px solid ' . ACCENT . '; background: ' . FILL_LIGHT . '; font-size: 12px; font-weight: bold; padding: 6px 10px; text-transform: uppercase; letter-spacing: 0.5px; }

    .inputs-table { margin-bottom: 8px; }
    .dt-label { color: ' . INK_MUTED . '; font-size: 9px; padding: 4px 8px; width: 25%; border-bottom: 1px solid ' . BORDER_LIGHT . '; }
    .dt-value { font-weight: bold; padding: 4px 8px; width: 25%; border-bottom: 1px solid ' . BORDER_LIGHT . '; }

    .items-table, .bom-table { margin-bottom: 8px; }
    .items-table th, .bom-table th { background: ' . INK_DARK . '; color: #fff; font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.5px; padding: 6px 8px; text-align: left; }
    .items-table td, .bom-table td { padding: 5px 8px; border-bottom: 1px solid ' . BORDER_LIGHT . '; }
    .row-alt { background: ' . FILL_LIGHT . '; }
    .col-num, .col-unit { text-align: right; width: 12%; }
    .col-label { text-align: left; }

    .grand-total-row td { border-top: 2px solid ' . INK_DARK . '; border-bottom: none; padding-top: 8px; }
    .grand-total-label { text-align: right; font-weight: bold; font-size: 11px; }
    .grand-total-value { font-weight: bold; font-size: 12px; color: ' . ACCENT . '; }

    .results-row { margin-bottom: 4px; }
    .results-row + .results-row { margin-top: 4px; }
    .result-cell { border: 1px solid ' . BORDER_LIGHT . '; padding: 8px 10px; text-align: center; width: 25%; }
    .result-cell-empty { border: none; }
    .result-highlight { background: ' . ACCENT . '; border-color: ' . ACCENT . '; }
    .result-highlight .result-label, .result-highlight .result-value { color: #FFFFFF; }
    .result-label { font-size: 8px; text-transform: uppercase; letter-spacing: 0.5px; color: ' . INK_MUTED . '; margin-bottom: 3px; }
    .result-value { font-size: 15px; font-weight: bold; }

    .disclaimer { margin-top: 24px; padding-top: 10px; border-top: 1px solid ' . BORDER_LIGHT . '; font-size: 8px; color: ' . INK_MUTED . '; line-height: 1.5; }
    ';
}
